apiVersion: v1
kind: Service
metadata:
  name: hello-arc
  namespace: arc-demo
spec:
  type: NodePort
  selector:
    app: hello-arc
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
